%YAML 1.2
%TAG ! tag:fawkesrobotics.org,cfg/
---
# Configuration meta information document
include:
  # reads files ending in .yaml from modules.d config subdir
  - !ignore-missing conf.d/
  # Reads the host-specific configuration file, no failure if missing
  - !host-specific host.yaml
---
# Main configuration document

fawkes:

  # Main app relevant settings
  mainapp:
    # Size of BlackBoard memory segment; bytes
    blackboard_size: 2097152
    # Desired loop time of main thread, 0 to disable; microseconds
    desired_loop_time: 33333

    # Maximum time a thread may run per loop, 0 to disable; microseconds
    max_thread_time: 66666

    # Uncomment the following to get a debug log file each time you
    # run fawkes independent of the log level.
    #loggers: console;file/debug:debug.log

    # Enable to redirect stderr to the log. If you have mis-behaving
    # third-party code this can come in handy to keep records of what's
    # going on for later analysis.
    log_stderr_as_warn: true

    net:
      # Port for Fawkes Network Protocol service; TCP port
      tcp_port: !tcp-port 1910

      # Name for Fawkes service, announced via Avahi,
      # %h is replaced by short hostname
      service_name: "Fawkes on %h"

      # Enable or disable IPv4 or IPv6 server port

      # Set "listen" value to bind to a specific IP address of the
      # host, rather than to "any" address, example shows how to bind
      # for connections from the local host only
      ipv4:
        enable: true
        #listen: !ipv4 127.0.0.1

      ipv6:
        enable: true
        #listen: !ipv6 "::1"

# Log level for ballposlog example plugin; sum of any of
# debug=0, info=1, warn=2, error=4, none=8
ballposlog/log_level: 0


# More configuration values can be found in the files mentioned
# above in the meta config document regarding includes.
