# Fawkes Buildkite Pipeline

merged-pr-plugin: &merged-pr-plugin
  seek-oss/github-merged-pr#v0.0.6:
    mode: checkout

steps:
  - label: ":fedora: Fedora"
    command: .buildkite/build
    plugins:
      <<: *merged-pr-plugin
      docker#v1.4.0:
        image: timn/fawkes-builder:fedora28-kinetic
        always-pull: true
        mounts:
          - /var/lib/buildkite-agent/ccache_fedora:/var/cache/ccache
        debug: true

  - label: ":ubuntu: Ubuntu"
    command: .buildkite/build
    plugins:
      <<: *merged-pr-plugin
      docker#v1.4.0:
        image: timn/fawkes-builder:ubuntu1804-melodic
        always-pull: true
        mounts:
          - /var/lib/buildkite-agent/ccache_ubuntu:/var/cache/ccache
        debug: true

  - label: ":pencil: Checks"
    command: .buildkite/check
    plugins:
      <<: *merged-pr-plugin
      docker#v1.4.0:
        image: timn/fawkes-builder:fedora28-kinetic
        always-pull: true
        debug: true
